INSERT INTO `destination`(`des_id`, `place`, `locality`, `Height_feet`, `Height_m`, `difficulty`, `season`, `picture`, `desc`) 
VALUES ('','Matheran Trek','Matheran','2506','763.8288','Medium','March to May','','Matheran, with its amicable climate and various trekking trails, attracts tourists the year round. There are almost 28 view-points scattered all around the place. One Tree Hill is one of them. Amongst the various trekking routes, the most famous one goes through the Garbert Plateau. Apart from this, trekking to Chanderi caves is an adventure in itself. Kalavantin Pinnacle Trek allows you to explore the fort at the peak.')
,('','Kalsubai Trek','Igatapuri Taluka','5400','1645.92','Medium to Hard','June to September','','alsubai, with a height of 5,400ft, is the highest peak in the Sahyadri mountain ranges. It’s also a part of the Kalsubai Harishchandragad Wildlife Sanctuary which extends from Kalasubai to Harischandragad. Trekking here is best experienced during the rainy season. Once comes across drenched green valleys, cool winds, hovering clouds and thrilling waterfalls during this time. From the peak, one can spot places like Ahivant, Saptashrungi gad and Markindya, beside others.')
,('','Korigad Fort Trek','Lonavala','3050','929.64','Easy','Throughout the year','','The impressive Korigad Fort is located about 20km away from Lonavala in Pune district. Korigad Fort Trek is amongst the popular treks in Maharashtra. There are two routes to reach the peak. One is from a village called Peth Shahpur and the other is from Ambavne village. One finds two lakes upon reaching the top of the fort. A temple to the patron goddess Korai Devi exists here, along with other smaller temples dedicated to Shiva and Vishnu. One can also walk along the entire perimeter of the wall of this fort.')
,('','Lohagarh Trek','Near Lonavala','3450','1051.56','Easy','June to February','','Chatrapati Shivaji Maharaj was famous for his forts scattered all around Maharashtra, and Lohagarh Iron Fort is one of them. Seated on a single side range of the Sahyadris, it divides the basins of Indranayi and Pavna. The four large gates of Lohagarh Fort are still in an impressive condition after so many years. Some of the other attractions here are The Ganesh Darwaja, The Narayan Darwaja and The Hanuman Darwaj.')
,('','Tikona Trek','Near Kamshet','3500','1066.8','Easy','September to March','','Tikona, also known as Vitandgad, lies near Kamshet around 60km from Pune. It’s an impressive and dominating hill fort in Maval in Western India. The hill, measuring upto 3500ft, derives its name from its pyramidal shape. As a trekking destination, it’s famous for its large doors, seven water tanks, temple of ‘Trimbakeshwar Mahadev’ and some Satvahan Caves. At the summit, one comes across the Pawana Lake. One can get spectacular views of the Pawna dam from here.')
,('','Rajmachi Trek','Near Lonavala','2710','826.008','Easy','June to September','','Rajmachi, located around 15km from Lonavala, is one of the most popular trekking destinations in India. There are two forts here, namely, Shrivardhan and Manaranjan. Located on the historical trade route, they provide mesmerizing views of the valley. The entire route is enveloped by dense forests on both sides. One can approach this place from two routes. One from Karjat, and the other from Lonavala.')
,('','Ratangad Trek','Ratanwadi','4250','1295.4','Medium','May to September','','From Ratangad, one can get incredible views of the Sahaydri Ranges near the Bhandardara Lake. Situated amidst the forest in Bhandardara hill, it still showcases the remains of a fortress with bastions and stone walls. This place also possesses a natural rock peak with a cavity atop it, which is called “Nedhe,” or “Eye of the Needle.” The base village Ratanwadi is approachable by boat from Bhandardara.')
,('','Peb Vikatgad Trek','Karjat','2100','640.08','Medium','Throughout the year','','Peb Vikatgad Trek brings alive the pleasures of trekking in monsoons. Although it derives its name from the Goddess Pebi, it has been named “Vikatgad” due to its resemblance to Lord Ganesh – an elephant god. Vikatgad Fort lies just 4km away from Neral station. This trail presents a mixture of rocky paths, forests, caves and ladders, thus making it extremely exciting and adventurous. It is said that Shivaji Maharaj used the caves in the fort as silos for storing grains.')
,('','Rajgad Fort Trek','Gunjavane','2901','884.2248','Medium','October to March','','Rajgad Fort is one of the grand forts located in the Sahaydri Range. This place is a trekker’s delight. Much of the fortifications of this fort still remains intact. The highest part of the fort has remains of caves, water cisterns and palaces. One can get incredible views of the magnificent Sahyadri range, when the entire place is bathed with blossoming flowers. This fort also possesses great historical significance.')
,('','Raigad Fort Trek','Raigad','2700','822.96','Medium','November to March','','Raigad Fort is undoubtedly one of the magnificent fortresses in Maharashtra. Located 125km away from Pune, it serves as one of the prominent getaways for locals. This magnificent fort is located at an altitude of 4,350ft. Approximately 1400-1450 steps lead up to the fort. The jungle trail that leads to the fort is itself an exciting one. Some of the structures inside the fort are Queen’s Quarters, Public Durbar and Watch Towers.')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')
VALUES ('','','','','','','','','')


UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Matheran Trek.jpg') WHERE place = 'Matheran Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Kalsubai Trek.jpg') WHERE place = 'Kalsubai Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Korigad Fort Trek.jpg') WHERE place = 'Korigad Fort Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Lohagarh Trek.jpg') WHERE place = 'Lohagarh Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Tikona Trek.jpg') WHERE place = 'Tikona Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Rajmachi Trek.jpg') WHERE place = 'Rajmachi Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Ratangad Trek.jpg') WHERE place = 'Ratangad Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Peb Vikatgad Trek.jpg') WHERE place = 'Peb Vikatgad Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Rajgad Fort Trek.jpeg') WHERE place = 'Rajgad Fort Trek';
UPDATE destination SET picture = LOAD_FILE('C:/xampp/htdocs/IP/images/Destination/Raigad Fort Trek.jpg') WHERE place = 'Raigad Fort Trek';
